# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Thomas Denewiler
email: tdenewiler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I work on robotic vehicles and like to write code that does fun things for a hobby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tdenewiler.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: tdenewiler

# Build settings
markdown: kramdown
